"""
     Django settings for water_monitor project.

     Generated by 'django-admin startproject' using Django 5.2.6.
     """

from pathlib import Path
from datetime import timedelta

     # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

     # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#^3g-q4$ql51xg(o*(9iw^lby(*d9btw8a+p#w@v!sf!g^e%#*'

     # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

     # Application definition
INSTALLED_APPS = [
         'django.contrib.admin',
         'django.contrib.auth',
         'django.contrib.contenttypes',
         'django.contrib.sessions',
         'django.contrib.messages',
         'django.contrib.staticfiles',

         # Thư viện bên thứ 3
         'rest_framework',
         'rest_framework_simplejwt',

         # App của dự án
         'monitoring',
     ]

MIDDLEWARE = [
         'django.middleware.security.SecurityMiddleware',
         'django.contrib.sessions.middleware.SessionMiddleware',
         'django.middleware.common.CommonMiddleware',
         'django.middleware.csrf.CsrfViewMiddleware',
         'django.contrib.auth.middleware.AuthenticationMiddleware',
         'django.contrib.messages.middleware.MessageMiddleware',
         'django.middleware.clickjacking.XFrameOptionsMiddleware',
     ]

ROOT_URLCONF = 'water_monitor.urls'

TEMPLATES = [
         {
             'BACKEND': 'django.template.backends.django.DjangoTemplates',
             'DIRS': [BASE_DIR / 'templates'],  # Thêm đường dẫn đến thư mục templates chính
             'APP_DIRS': True,
             'OPTIONS': {
                 'context_processors': [
                     'django.template.context_processors.request',
                     'django.contrib.auth.context_processors.auth',
                     'django.contrib.messages.context_processors.messages',
                 ],
             },
         },
     ]
WSGI_APPLICATION = 'water_monitor.wsgi.application'

     # Database
DATABASES = {
         'default': {
             'ENGINE': 'django.db.backends.sqlite3',
             'NAME': BASE_DIR / "db.sqlite3",
         }
     }

     # Password validation
AUTH_PASSWORD_VALIDATORS = [
         {
             'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
         },
         {
             'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
         },
         {
             'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
         },
         {
             'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
         },
     ]

     # Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

     # Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Thêm nếu bạn có thư mục static riêng

     # Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

     # 🔑 Custom user model
AUTH_USER_MODEL = 'monitoring.User'

     # ⚙️ REST Framework config
REST_FRAMEWORK = {
         'DEFAULT_AUTHENTICATION_CLASSES': (
             'rest_framework_simplejwt.authentication.JWTAuthentication',
         ),
         'DEFAULT_PERMISSION_CLASSES': (
             'rest_framework.permissions.IsAuthenticated',
         ),
     }

     # 🔒 JWT settings
SIMPLE_JWT = {
         'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
         'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
         'AUTH_HEADER_TYPES': ('Bearer',),
     }

     # 🔐 Authentication settings
LOGIN_URL = '/login/'  # Khớp với URL trong urls.py
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect sau khi login thành công
LOGOUT_REDIRECT_URL = '/login/'  # Redirect sau khi logout thành công
# Email configuration (cần cấu hình theo email server thực tế)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Hoặc SMTP server của bạn
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'  # Thay bằng email của bạn
EMAIL_HOST_PASSWORD = 'your-app-password'  # Thay bằng password ứng dụng
DEFAULT_FROM_EMAIL = 'Water Monitor <noreply@watermonitor.com>'

# Site URL for password reset
SITE_URL = 'http://localhost:8000'  # Thay bằng domain thực tế