# Generated by Django 5.2.6 on 2025-09-17 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('type', models.CharField(choices=[('RULE', 'Rule'), ('AI', 'AI'), ('FORECAST', 'Forecast')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACK', 'Acknowledged'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ph', models.FloatField()),
                ('tds', models.FloatField()),
                ('ntu', models.FloatField()),
                ('battery', models.FloatField(blank=True, null=True)),
                ('signal', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
