# Generated by Django 5.2.6 on 2025-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_useractionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
