# Generated by Django 5.2.6 on 2025-10-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
