# Generated by Django 5.2.6 on 2025-10-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_report_options_alter_report_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.AddField(
            model_name='report',
            name='created_by_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
