# Generated by Django 5.2.6 on 2025-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_remove_report_created_by_report_created_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Báo cáo hàng ngày'), ('weekly', 'Báo cáo hàng tuần'), ('monthly', 'Báo cáo hàng tháng'), ('incident', 'Báo cáo sự cố')], max_length=20),
        ),
    ]
